### ISSUE TITLE
Use of Box<dyn Error> prevents Wherr from working with anyhow

### ISSUE THREAD

**Issue by smsutherland** [joelonsql/wherr#1]
Being able to work with the [anyhow](https://crates.io/crates/anyhow) crate would make this crate much more ergonomic for use in existing code. Currently, wherr uses `Box<dyn Error>` as it's inner error type and error returned from wherrapper. This is not Sized, Send, or Sync, meaning it cannot be converted into anyhow's [Error](https://docs.rs/anyhow/latest/anyhow/struct.Error.html#impl-From%3CE%3E-for-Error) type. Based on some testing I've done locally, the API of anyhow::Error is similar enough to that of Box<dyn Error> that there would be nearly no code changes necessary between the two implementations.

I'd like to propose the existence of a feature flag which would switch wherr to use anyhow::Error as its inner error type. This could either change the behavior of the #[wherr] macro directly, or enable the existence of a #[wherr_anyhow] macro, whichever seems most convenient (though I lean toward the former).

If this is something you're interested in, I'd be happy to submit a PR implementing these changes.

**Comment by joelonsql** [comment]
Hi @smsutherland, nice to meet you!

I think better integration with `anyhow` would be great!

Given all the extremely valuable feedback from fellow Rustaceans in the [Hacker News](https://news.ycombinator.com/item?id=37232229) thread, I think it would be interesting to explore the `#[track_caller]` + `std::panic::Location::caller()` idea, and consider it for a new major version of this crate. It would be interesting to think about how anyhow integration would work with that idea.

**Comment by smsutherland** [comment]
Use of `#[track_caller]` is interesting. Like you, I hadn't heard of it until the Hacker News thread. I think anyhow integration would work well with this implementation (I'll try to experiment with this when I have time to). As for optimization, there's more to think about here. Using `&'static Location` makes a Wherr 3 words long (2 words when using `anyhow::Error` instead of  `Box<dyn Error>`) which would probably speed things up despite the one-time penalty of the extra indirection from the reference. On the other hand, if the `T` in `Result<T, E>` is bigger than `E` then the size of the result type will be determined by that of `T` and not `E` so I could be wrong on that count as well.

Well, whatever the case, when I have the time I'll submit a PR with anyhow integration under the current implementation. I'll also try to start exploring `#[track_caller]` as well, but further discussion of that should probably go in its own issue just for organization's sake.

**Comment by joelonsql** [comment]
@smsutherland Thanks for the [PR](https://github.com/joelonsql/wherr/pull/2). I'm awaiting your feedback on this commit: https://github.com/joelonsql/wherr/commit/62628f49d3482a29e3a9da084e0b753a4c6bb119

**Comment by joelonsql** [comment]
Pushed: [Integrate optional anyhow support via feature flag](https://github.com/joelonsql/wherr/commit/5f41e5a050109f1cdfe05a0e539ce40860fb9d0e)
